### ISSUE TITLE
kitemarking

### ISSUE THREAD

**Issue by benmarwick** [sje30/eglen2015#1]
Hi Stephen, 

I was interested to see that part two of this paper deals with some of the topics discussed in the INCF meeting in Dec, I look forward to reading it!

On the topic of kitemarking, it might also be relevant to note the badging system that has been adopted by a few journals, as a signal for code and data sharing (I've been peppering journals in my field to adopt it also). Here are a few relevant links, etc.:

http://pss.sagepub.com/content/25/8.toc.pdf
Table of Contents from August's issue of Psych Science (showing badges)

http://pss.sagepub.com/content/25/8/1571.full
a manuscript from the same issue (badges at the top of the first page, and then again at the end of the article along with the URLs to the evidence for the badges).

Additionally, all of the articles in this special issue of Social Psychology (with the exception of the editorial) have been awarded badges. In Social Psychology, the badges appear only at the end of the articles.

An example of Psychological Science badged article:
http://pss.sagepub.com/content/25/12/2199.full

Psychological Science's Explanation of Open Practices
http://www.psychologicalscience.org/index.php/publications/journals/psychological_science/ps-submissions#OPEN
And about the badges
http://www.psychologicalscience.org/index.php/publications/journals/psychological_science/badges

Cognition data policy:
http://www.sciencedirect.com.offcampus.lib.washington.edu/science/article/pii/S0010027714002248

And you've probably seen the recent editorial from 'Scientific Data" that says they're going to demand code availability where it seems necessary, and recommend github plus a DOI-issuing repository: http://blogs.nature.com/scientificdata/2015/02/19/code-sharing-tips/

best, 

Ben

**Comment by sje30** [comment]
Hi Ben,

Thanks very much for these comments.  I will check them out!

Best wishes, Stephen
