### ISSUE TITLE
buildVignettes fails with layers_csn3.pdf not found.

### ISSUE THREAD

**Issue by benmarwick** [sje30/eglen2015#3]
Not quite sure why this is happening, since I can see the pdf file in the directory with the Rnw file... I'm doing this in the RStudio I get from `docker run -d -p 8787:8787 sje30/eglen2015` I've never had any problem like this with my own work, though I use a 'figures' directory within the vignette directory to hold this kind of thing. What do you think? Can you build the vignette in the docker container? 

```
> tools::buildVignettes("eglen2015")
Read 4 items
Read 222 items
Read 116 items
Read 10 items
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'eglen2015.tex' failed.
LaTeX errors:
! Package pdftex.def Error: File `layers_csn3.pdf' not found.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
```

**Comment by sje30** [comment]
Thanks for checking this Ben!  I think I know the problem -- that pdf
(layers_csn3.pdf) is a diagram that was made from inkscape, and I forgot
to include in the .install_extras file.  Now trying a new build to see
if that fixes it!

Stephen

**Comment by sje30** [comment]
Can you please try again?  It works for me now.

**Comment by benmarwick** [comment]
Yes, that's done the trick, `tools::buildVignettes("eglen2015")` results in the PDF now.  I hadn't heard of`.install_extras` before, good to know about that! 

I was the rOpenSci workshop two weeks ago and we discussed R packages as research compendia  (these threads sum up the major topics of discussion: [1](https://github.com/ropensci/unconf/issues/11), [2](https://github.com/ropensci/unconf/issues/31)) and I heard of a few people who are using the package structure, but including a `manuscript` directory  that contains the Rmd/Rnw and styling files, for example: https://github.com/cboettig/nonparametric-bayes I'm going with the vignette-as-manuscript approach as you have here, because I like to have the build and check mechanics work on my manuscript as well as code. But there are a few people who see vignettes in a more narrow way, it seems.
